# Variables

In [1]:
import torch
from torch.autograd import Variable

In [2]:
a = Variable(torch.ones(2, 2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
# Not a variable
torch.ones(2, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [4]:
# Behaves similarly to tensors
b = Variable(torch.ones(2, 2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [5]:
print(a * b)
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


# Gradients

In [17]:
x = Variable(torch.ones(2), requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

In [18]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

In [19]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

In [20]:
o.backward()

In [21]:
x.grad

tensor([10., 10.])

In [22]:
# backward in detail
o.backward(torch.FloatTensor([1.0, 1.0]))


RuntimeError: Mismatch in shape: grad_output[0] has a shape of torch.Size([2]) and output[0] has a shape of torch.Size([]).